[package]
name = "client"
version = "0.1.0"
authors = ["jakearmendariz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dns-lookup = "1.0.4"
stopwatch = "0.0.7"
openssl = "0.10"
openssl-sys = "0.9"